using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IngredientServer.Core.Entities;

/// <summary>
/// Cached food recipes generated by AI - public cache shared by all users
/// This table stores food recipes to avoid calling Azure OpenAI API repeatedly for the same requests
/// </summary>
public class CachedFood
{
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// Food name (normalized for searching)
    /// </summary>
    [Required]
    [StringLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Search key - combination of food name and ingredients (normalized, lowercase)
    /// Used for fast lookup: "food_name|ingredient1|ingredient2|..."
    /// </summary>
    [Required]
    [StringLength(500)]
    public string SearchKey { get; set; } = string.Empty;

    [StringLength(1000)]
    public string? Description { get; set; }

    [Required]
    public int PreparationTimeMinutes { get; set; }

    [Required]
    public int CookingTimeMinutes { get; set; }

    [Required]
    [Column(TypeName = "decimal(8,2)")]
    public decimal Calories { get; set; }

    [Required]
    [Column(TypeName = "decimal(8,2)")]
    public decimal Protein { get; set; }

    [Required]
    [Column(TypeName = "decimal(8,2)")]
    public decimal Carbohydrates { get; set; }

    [Required]
    [Column(TypeName = "decimal(8,2)")]
    public decimal Fat { get; set; }

    [Required]
    [Column(TypeName = "decimal(8,2)")]
    public decimal Fiber { get; set; }

    [StringLength(500)]
    public string? ImageUrl { get; set; }

    // Recipe instructions/steps - stored as JSON in database
    [Required]
    [Column(TypeName = "json")]
    public List<string> Instructions { get; set; } = new List<string>();

    [Required]
    [Column(TypeName = "json")]
    public List<string> Tips { get; set; } = new List<string>();

    // Difficulty level (1-5 scale)
    [Range(1, 5)]
    public int DifficultyLevel { get; set; } = 1;

    // Ingredients used in this recipe - stored as JSON
    [Required]
    [Column(TypeName = "json")]
    public List<CachedFoodIngredient> Ingredients { get; set; } = new List<CachedFoodIngredient>();

    /// <summary>
    /// Number of times this cached food has been used
    /// </summary>
    public int HitCount { get; set; } = 0;

    /// <summary>
    /// Last time this cache was accessed
    /// </summary>
    public DateTime LastAccessedAt { get; set; } = DateTime.UtcNow;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Computed property for total time
    [NotMapped]
    public int TotalTimeMinutes => PreparationTimeMinutes + CookingTimeMinutes;
}

/// <summary>
/// Ingredient information stored in cached food
/// Note: IngredientId is NOT stored here because each user has different ingredient IDs
/// We store only IngredientName and map to user's ingredient ID when converting
/// </summary>
public class CachedFoodIngredient
{
    /// <summary>
    /// Ingredient name (used to find user's ingredient by name)
    /// </summary>
    public string IngredientName { get; set; } = string.Empty;
    
    /// <summary>
    /// Quantity needed for this recipe
    /// </summary>
    public decimal Quantity { get; set; }
    
    /// <summary>
    /// Unit of measurement
    /// </summary>
    public IngredientUnit Unit { get; set; }
}

