// This file is auto-generated by EF Core migrations
// It will be updated automatically when migrations are applied

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using IngredientServer.Infrastructure.Data;

#nullable disable

namespace IngredientServer.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            // This snapshot will be auto-generated by EF Core
            // Keeping it minimal for now
        }
    }
}

